steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    timeout: '600s'  # Adjust timeout as needed

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    timeout: '600s'  # Adjust timeout as needed

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', 'build/', 'gs://configbuckett']
  
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t','asia-south1-docker.pkg.dev/block-convey-p1/react-repo/my-app:${SHORT_SHA}', '.' ]
          
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/block-convey-p1/react-repo/my-app:${SHORT_SHA}']

  #   # Pull Docker image from Artifact Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['pull', 'asia-south1-docker.pkg.dev/block-convey-p1/react-repo/my-app:${SHORT_SHA}']

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args: [
      'deploy',
      'react-app-deployment',
      'asia-south1-docker.pkg.dev/block-convey-p1/react-repo/my-app:${SHORT_SHA}',
      'asia-south1',
      'autopilot-cluster-1',
    ]

substitutions:
  _BUCKET_NAME: configbuckett

images:
  - asia-south1-docker.pkg.dev/block-convey-p1/react-repo/my-app:${SHORT_SHA}

