apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 2 # Number of desired pods
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app-container
          image: asia-south1-docker.pkg.dev/block-convey-p1/react-repo/my-app:dc404ca
          ports:
            - containerPort: 80 # Port your React app listens on
