apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: Load balancer
  selector:
    app: simple-app
  ports:
    - port: 80
      protocol: TCP

      # protocol: TCP







---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "nginx-1-service"
  namespace: "default"
  labels:
    app: "nginx-1"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "nginx-1"
  type: "LoadBalancer"
  loadBalancerIP: ""




