steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    timeout: '600s'  # Adjust timeout as needed

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    timeout: '600s'  # Adjust timeout as needed

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', 'build/', 'gs://configbuckett']

substitutions:
  _BUCKET_NAME: configbuckett